/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms.gui;

import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Date;

/**
 *
 * @author DELL
 */
public class UpdateMedicine extends javax.swing.JFrame {

    public String numberPattern = "^[0-9]*$";

    /**
     * Creates new form UpdateMedicine
     */
    public UpdateMedicine() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        medicineidTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        companynameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        manuDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        expDate = new com.toedter.calendar.JDateChooser();
        updateBtn = new javax.swing.JButton();
        addquantityTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 13, -1, -1));

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/Images/close.png"))); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 13, 36, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 850, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Medicine Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 110, 78, -1));

        medicineidTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(medicineidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 107, 300, -1));

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/Images/search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 103, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 150, 300, -1));

        nameTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 183, 300, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 222, 300, -1));

        companynameTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        companynameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companynameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(companynameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 255, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 295, 300, -1));

        quantityTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 328, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Add Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 370, -1, 16));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 368, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Price Per Unit");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 150, 300, -1));

        priceTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 183, 300, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Manufactured Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 222, 300, -1));

        manuDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(manuDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 255, 300, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Expiry Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 295, 300, -1));

        expDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(expDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 328, 300, -1));

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/Images/save.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 368, -1, -1));

        addquantityTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pms/Images/all_pages_background.png"))); // NOI18N
        getContentPane().add(addquantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        int checkMedicineExist = 0;
        String uniqueId =medicineidTxt.getText();
        if(uniqueId.equals("")){
            JOptionPane.showMessageDialog(null,"Medicine Id field is required.");
        }else{
            try {
                Connection con=ConnectionProvider.getConnection();
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("SELECT * FROM medicine WHERE uniqueId='"+uniqueId+"'");
                while(rs.next()){
                    medicineidTxt.setEditable(false);
                    nameTxt.setText(rs.getString("name"));
                    companynameTxt.setText(rs.getString("companyName"));
                    quantityTxt.setText(rs.getString("quantity"));
                    priceTxt.setText(rs.getString("price"));
                    manuDate.setDate(rs.getDate("manufacturedDate"));
                    expDate.setDate(rs.getDate("expiryDate"));
                    quantityTxt.setEditable(false);
                    checkMedicineExist=1;
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            if(checkMedicineExist==0){
                JOptionPane.showMessageDialog(null,"Medicine Id does not exist");
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void companynameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companynameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companynameTxtActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String uniqueId=medicineidTxt.getText();
        String name=nameTxt.getText();
        String companyname=companynameTxt.getText();
        String quantity=quantityTxt.getText();
        String price=priceTxt.getText();
        Date mDate=manuDate.getDate();
        Date eDate=expDate.getDate();
        String addQuantity=addquantityTxt.getText();
        int totalQuantity=0;
        if(addQuantity.equals("")){
            totalQuantity=Integer.parseInt(quantity);
        }else{
            totalQuantity=Integer.parseInt(quantity)+Integer.parseInt(addQuantity);
            System.out.println(""+totalQuantity);
        }
        if(uniqueId.equals("")){
            JOptionPane.showMessageDialog(null,"Medicine Id field is required.");
        }else if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required.");
        }else if(companyname.equals("")){
            JOptionPane.showMessageDialog(null,"Company Name field is required.");
        }else if(!addQuantity.matches(numberPattern)){
            JOptionPane.showMessageDialog(null,"Add Quantity field is invalid.");
        }else if(price.equals("")){
            JOptionPane.showMessageDialog(null,"Price field is required.");
        }else if(!price.matches(numberPattern)){
            JOptionPane.showMessageDialog(null,"Price field is invalid.");
        }else if(mDate.equals("")){
            JOptionPane.showMessageDialog(null,"Manufactured Date field is required.");
        }else if(eDate.equals("")){
            JOptionPane.showMessageDialog(null,"Expiiry Date field is required.");
        }else{
            try {
                Connection con=ConnectionProvider.getConnection();
                PreparedStatement ps=con.prepareStatement("UPDATE medicine SET name=?,companyName=?,quantity=?,price=?,manufacturedDate=?,expiryDate=? WHERE uniqueId=?");
                ps.setString(1,name);
                ps.setString(2,companyname);
                ps.setString(3,""+totalQuantity);
                ps.setString(4, price);
                ps.setDate(5,new java.sql.Date(mDate.getTime()));
                ps.setDate(6,new java.sql.Date(eDate.getTime()));
                ps.setString(7,uniqueId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Medicine updated successfully");
                setVisible(false);
                new UpdateMedicine().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addquantityTxt;
    private javax.swing.JTextField companynameTxt;
    private javax.swing.JButton exitBtn;
    private com.toedter.calendar.JDateChooser expDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField5;
    private com.toedter.calendar.JDateChooser manuDate;
    private javax.swing.JTextField medicineidTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
